Feat/pm 1063/catalog carousel
fe-playmaker/fe-playmaker pull request #102
Opened 2023-06-28 21:07 UTC by mati-1

[PM-1063](https://playmakerpro.atlassian.net/browse/PM-1063)

- added simple carousel (without item variants)
- corrected all styles from figma at register pages

2023-06-29 10:08 UTC, dejwi requested changes
<img width="432" alt="image" src="https://github.com/fe-playmaker/fe-playmaker/assets/80927085/08a57852-0bb7-4376-b285-31b7bffa949a">

odkrywaj and wiecej are not on the same level

on mobile height of card is too big and dots should be hidden

<img width="1001" alt="image" src="https://github.com/fe-playmaker/fe-playmaker/assets/80927085/a3b0de27-d9e8-40f4-98b2-c406afbbd932">

it isn't responsive

and maybe choose a different image for this ? idk where you've found this one but it looks stretched XD

2023-06-29 10:08 UTC, dejwi commented on components/login-register/common/Input/checkbox.tsx
> +      )}
I don't think it should be here, maybe pass a `children` prop and do stuff there

2023-06-29 10:08 UTC, dejwi commented on components/login-register/register/pages/profile-type-page/profile-type-page.tsx
> +      otherObligationsValue: customProfileType,
maybe something like this ?
```suggestion
      customProfileTypeName: customProfileType,
```

2023-06-29 22:29 UTC, mati-1 commented on components/login-register/register/pages/profile-type-page/profile-type-page.tsx
> +      otherObligationsValue: customProfileType,
XDD

2023-07-03 19:54 UTC, mati-1 commented
when pagination is extended, layout extends beyond the screen

![image](https://github.com/fe-playmaker/fe-playmaker/assets/91088258/5a2e3cb2-f52f-425c-a710-b5bd393c5269)

2023-07-05 18:09 UTC, dejwi requested changes
BRO PLEASE FOLLOW FIGMA STYLES CAREFULLY !!😭

In next pr's please don't mix stuff, carousel and register stuff should be in separate pr's

Maybe I missed some things so please double check

--

(figma)
<img width="300" alt="image" src="https://github.com/fe-playmaker/fe-playmaker/assets/80927085/5fff81aa-dcf9-4e2b-9a84-cf4a4b70dd38">

(our)
<img width="300" alt="image" src="https://github.com/fe-playmaker/fe-playmaker/assets/80927085/6bd0fc99-359f-4826-8f65-f87991c5614f">

--

dots should be higher check figma
<img width="159" alt="image" src="https://github.com/fe-playmaker/fe-playmaker/assets/80927085/36137f35-e065-4749-8719-97d97ed8c62e">

--

it should be further from footer(mobile)
<img width="527" alt="image" src="https://github.com/fe-playmaker/fe-playmaker/assets/80927085/7521dcf8-56fb-41c8-a822-19a1502eae0e">

2023-07-05 18:33 UTC, mati-1 commented
> (figma) <img alt="image" width="300" src="https://user-images.githubusercontent.com/80927085/251235923-5fff81aa-dcf9-4e2b-9a84-cf4a4b70dd38.png">
> 

shadow at the right side is only for mobile devices? I didnt create it cos this component will be a little different in the future (kamil said this)

2023-07-05 18:39 UTC, mati-1 commented
and you re right bout register stuff. I wasnt thought like that xD

2023-07-05 18:42 UTC, mati-1 commented
i changed the footer padding in the teams catalog branch, dont look at it there

2023-07-06 09:56 UTC, dejwi requested changes
I didn't mean the shadow, items look different
<img width="200" alt="image" src="https://github.com/fe-playmaker/fe-playmaker/assets/80927085/6b37e346-8da2-4d8c-99aa-af788cbe960a">
vs
<img width="200" alt="image" src="https://github.com/fe-playmaker/fe-playmaker/assets/80927085/6cadc8a0-d2e2-47b5-96f5-8eb50538d355">

and on mobile this section should be further from pagination

2023-07-06 09:56 UTC, dejwi commented on components/catalogs/players/carousel/carousel-section.tsx
> +export const CarouselSection = () => (
```suggestion
export const DiscoverCarouselSection = () => (
```

2023-07-06 09:56 UTC, dejwi commented on components/catalogs/players/carousel/carousel-section.tsx
> +)
it's reused in clubs catalog as well so better place it in `catalogs/common/DiscoverCarousel` (use and rename already existing folder there ~`CatalogCarousel` )

2023-07-07 10:30 UTC, dejwi approved these changes
🎉

2023-07-07 10:30 UTC, merged