Refactor/pm 20-207/club selection
fe-playmaker/fe-playmaker pull request #114
Opened 2023-07-26 20:14 UTC by mati-1

[PM20-207](https://playmakerpro.atlassian.net/browse/PM20-207)

2023-07-27 16:34 UTC, dejwi requested changes
🌝🌚🌝🌚🌝🌚🌝🌚🌝🌚🌝🌚🌝

2023-07-27 16:34 UTC, dejwi commented on components/login-register/register/pages/adding-club-page/modals/competitions-modal.tsx
> +        additionalText={isActualSeason ? 'Aktualny sezon rozgrywkowy' : ''}
It's competitions modal 🌝

2023-07-27 16:34 UTC, dejwi commented on components/login-register/common/NothingMessage/nothing-message.tsx
>    </motion.div>
nooo they removed clear btn only for clubs modal, it's still there in previous stuff

Mybe make the prop onClear optional and only render it when it's passed

2023-07-27 16:34 UTC, dejwi commented on components/login-register/common/NothingMessage/nothing-message.tsx
>    </motion.div>
nooo they removed clear btn only for clubs modal, it's still there in previous stuff

Mybe make the prop onClear optional and only render it when it's passed

2023-07-27 19:46 UTC, mati-1 commented on components/login-register/register/pages/adding-club-page/modals/competitions-modal.tsx
> +        selected={selected.includes(id)}
it works fine bro

2023-07-27 19:50 UTC, mati-1 commented on components/login-register/common/Input/select-input.tsx
> +  onClose?: () => void
look at the base data form in that case opening a new modal with onclick on the selected input, onSave n onClose isnt necessary

2023-07-27 19:50 UTC, mati-1 commented on components/login-register/register/pages/adding-club-page/adding-club-form.tsx
> +    selectedSeason.includes(id),
it works fine bro

2023-07-27 19:51 UTC, mati-1 commented on components/login-register/common/NothingMessage/nothing-message.tsx
>    </motion.div>
goddamn

2023-07-27 19:54 UTC, dejwi commented on components/login-register/register/pages/adding-club-page/modals/competitions-modal.tsx
> +        selected={selected.includes(id)}
but don't do that, why would you switch to that right now from equals signs ? At first I thought that was an array type and I was confused

please change it

2023-07-27 20:02 UTC, dejwi commented on components/login-register/common/Input/select-input.tsx
> +  onClose?: () => void
hmmmmm okay

2023-07-27 20:23 UTC, mati-1 commented on components/login-register/register/pages/adding-club-page/modals/competitions-modal.tsx
> +        additionalText={isActualSeason ? 'Aktualny sezon rozgrywkowy' : ''}
😵‍💫 😵‍💫 😵‍💫 😵‍💫 😵‍💫

2023-07-28 07:41 UTC, mati-1 commented on components/login-register/register/pages/adding-club-page/modals/competitions-modal.tsx
> +        selected={selected.includes(id)}
sure

2023-07-30 10:57 UTC, dejwi requested changes
bro get these paddings right I know you can do it match the figma, check every modal

compare px in padding using computed tab in inspect element on browser

2023-07-30 10:57 UTC, dejwi commented on components/login-register/common/NothingMessage/nothing-message.tsx
>        Brak wyników dla wpisanej frazy
and please don't forget restore the text that is with clear btn

2023-07-30 10:57 UTC, dejwi commented on components/common/Modal/header.tsx
> +      'relative z-20 box-content flex flex-col px-6 pt-7 !pb-6 sd:px-8',
no bro this changes all modals and now padding are wrong on normal modals and there's no variant of modal that has different pt and pb

and do we need `searchInputInHeaderTop` prop ? can't we guess that based on presence of the title ?

2023-07-30 10:57 UTC, dejwi commented on components/login-register/register/pages/adding-club-page/modals/clubs-modal.tsx
>          modalTitle="Dodaj klub"
this modal has an arrow too

2023-07-31 14:39 UTC, mati-1 commented on components/common/Modal/header.tsx
> +      'relative z-20 box-content flex flex-col px-6 pt-7 !pb-6 sd:px-8',
good

2023-08-01 18:50 UTC, dejwi approved these changes
NICE

2023-08-01 20:49 UTC, merged