Refactor/pm20 266/modal header
fe-playmaker/fe-playmaker pull request #116
Opened 2023-07-27 14:48 UTC by mati-1

[PM20-266](https://playmakerpro.atlassian.net/browse/PM20-266)

2023-07-27 20:43 UTC, dejwi requested changes
you have to update styles as well bro, if you check the clubs modal search at least on mobile it should have smaller py and search&arrow are too far apart, on desktop arrow should be bigger

check things yourself too maybe there's something else

2023-07-27 20:43 UTC, dejwi commented on components/common/Modal/header.tsx
>  }
if you've added these props in IModalProps already, just add them to Pick

2023-07-27 20:43 UTC, dejwi commented on components/common/Modal/modal.tsx
> +                  {...props}
you can remove your changes from this file, if you won't separate these props they'll be passed with `{...props}`

2023-07-28 09:14 UTC, mati-1 commented on components/common/Modal/header.tsx
>  }
fr

2023-07-28 09:52 UTC, mati-1 commented on components/common/Modal/modal.tsx
> +                  {...props}
🤝

2023-07-28 16:42 UTC, closed without merging