added available soon at players catalog n empty state component
fe-playmaker/fe-playmaker pull request #117
Opened 2023-07-29 18:23 UTC by mati-1

[PM20-212](https://playmakerpro.atlassian.net/browse/PM20-212)

- added available soon view with query param
- added empty state component

2023-07-29 20:15 UTC, mati-1 commented
im not sure bout empty state component, is a cva needed?

2023-07-31 11:03 UTC, dejwi requested changes
I'll try later to make it work with import and .src, or you can try if you want I think we may only need some ts type declaration

Ideally I think it should work like

```ts
import BinocularsAnimation from '@/animations/bionculars.lottie'

....

<EmptyStateMessage
    title="Już wkrótce dostępne"
    text="Lista jest w trakcie przygotowywania. Włącz powiadomienie, a my
    poinformujemy Cię, gdy będzie dostepna."
    lottieAnimation={BinocularsAnimation.src}
/>
```

2023-07-31 11:04 UTC, dejwi commented
> im not sure bout empty state component, is a cva needed?

I feel like it's a overkill in this case

2023-07-31 12:57 UTC, mati-1 commented on components/common/EmptyStateMessage/empty-state-message.tsx
> +        className: 'w-[42px] h-[42px] sd:w-[56px] sd:h-[56px]',
i saw that when you did the w-px n you automatically converted to rem? lol

2023-07-31 12:58 UTC, mati-1 commented on components/common/EmptyStateMessage/empty-state-message.tsx
> +    )}
nice :)

2023-07-31 13:00 UTC, dejwi commented on components/common/EmptyStateMessage/empty-state-message.tsx
> +        className: 'w-[42px] h-[42px] sd:w-[56px] sd:h-[56px]',
it was probably a name of a precreated class not a custom px value inserted
I created classes with name like 3px to just find them faster XD

2023-07-31 13:03 UTC, mati-1 commented on components/common/EmptyStateMessage/empty-state-message.tsx
> +    )}
good, i didnt think bout that

2023-07-31 15:58 UTC, mati-1 commented on components/common/EmptyStateMessage/empty-state-message.tsx
> +        className: 'w-[42px] h-[42px] sd:w-[56px] sd:h-[56px]',
xD 💀

2023-08-01 06:34 UTC, dejwi requested changes

2023-08-01 06:34 UTC, dejwi commented on components/common/EmptyStateMessage/empty-state-message.tsx
> +    {lottieAnimation === 'binoculars' && (
```suggestion
    {lottieAnimation && (
```

2023-08-01 06:34 UTC, dejwi commented on components/common/EmptyStateMessage/empty-state-message.tsx
> +      </div>
loading needs to work as a single state of this component
<img width="626" alt="image" src="https://github.com/fe-playmaker/fe-playmaker/assets/80927085/d1492584-ed82-4a78-bd47-ac20b4fac277">

2023-08-01 07:04 UTC, mati-1 commented on components/common/EmptyStateMessage/empty-state-message.tsx
> +    {lottieAnimation === 'binoculars' && (
why something like this? maybe we'll add more animation in this component in the future

2023-08-01 07:18 UTC, dejwi commented on components/common/EmptyStateMessage/empty-state-message.tsx
> +      </div>
don't forget loading title and maybe add optional loadingDescription ?

2023-08-01 07:58 UTC, dejwi commented on components/common/EmptyStateMessage/empty-state-message.tsx
> +    {lottieAnimation === 'binoculars' && (
yea so why do we have to check this stricly, with more variants you would have to check every single one and it's pointless

2023-08-01 08:03 UTC, mati-1 commented on components/common/EmptyStateMessage/empty-state-message.tsx
> +    {lottieAnimation === 'binoculars' && (
fr, i forgot bout src XD

2023-08-02 13:44 UTC, dejwi approved these changes
picobello

2023-08-02 13:57 UTC, merged