Feat/pm 743/tab overview
fe-playmaker/fe-playmaker pull request #18
Opened 2023-02-17 00:26 UTC by mati-1

[PM-743](https://playmakerpro.atlassian.net/browse/PM-743)

Added slider section, base player info with soccer field section and experience table section
Added dummy data with useQuery hook

2023-02-17 10:38 UTC, dejwi reviewed
dummy-api/api stuff shouldn't be like that, don't use other endpoints, whole 'overview' tab has to have data in one separate endpoint/object

You can decouple interfaces if you want to separate things (like you separated experience.ts) but there has to be one complete overview data object/interface

So there has to be a `dummy-api/profile/overview.ts` file OR if you decouple things `dummy-api/profile/overview/overview.ts` that contains the main object/interface

and this means there has to be only one data hook that's used here `useProfileOverview`

Overall good job, I can see that you're improving💯

2023-02-17 10:38 UTC, dejwi commented on components/profile/overview/baseDataSection/baseDataSection.tsx
> +              <span className="flex items-center gap-2 text-darkAlpha-40">
correct color
```suggestion
          <div className="flex gap-3 font-inter text-body-sm font-medium">
            <span className=" w-[5rem] text-darkAlpha-20">{d.title}</span>
            <span className="text-darkAlpha-40">{d.content}</span>
          </div>
        ))}
      </div>
      <div className="relative grid grid-cols-2">
        <div className="flex flex-col gap-4 pt-6 pb-8">
          {soccerFieldData.map(d => (
            <div className="flex flex-col font-inter text-body-sm font-medium">
              <span className="text-darkAlpha-20">{d.title}</span>
              <span className="flex items-center gap-2 text-darkAlpha-40">
```

2023-02-17 10:38 UTC, dejwi commented on components/common/Heading/Heading.tsx
> +)
I think it should better be in `/components/profile/common`

2023-02-17 10:38 UTC, dejwi commented on components/common/SectionContainer/SectionContainer.tsx
> +)
same as in Heading

2023-02-17 10:38 UTC, dejwi commented on components/profile/overview/overview.tsx
> +    useProfileHeader('69')
Like I said in main comment, there has to be only one `useProfileOverview`

2023-02-17 10:38 UTC, dejwi commented on dummy-api/profile/header.ts
>    lastActivity: string
so please remove all your changes from this file

2023-02-17 10:38 UTC, dejwi commented on components/profile/overview/helpers.tsx
> +]
this data needs to come form `useProfileOverview` :) 

In this case wouldn't it be best if iconsUrl came from endpoint ? Just asking for opinion, because we have to remember there can be a lot these 'badges' and what if there's a new one ?

2023-02-18 14:02 UTC, dejwi reviewed
Niceeee, good job bro💪

and this `Heading`, `SectionContainer` I meant to move to for ex. `/components/profile/common/Heading`

2023-02-18 14:25 UTC, mati-1 commented on components/profile/overview/overview.tsx
> +      {isLoading ? (
what is this? I changed it after first cr 😮

2023-02-18 15:07 UTC, mati-1 commented on dummy-api/profile/overview.ts
> +  }
this wont work good, better way is to nest this data to freely use the spread operator and types in code

2023-02-18 15:14 UTC, mati-1 commented on dummy-api/profile/overview.ts
> +  }
this wont work good, better way is nest this data to freely use the spread operator and types in your code

2023-02-18 15:16 UTC, mati-1 commented on components/profile/overview/slider/slider.tsx
> +const SliderItem = ({ title, icon }: { title: string; icon: string }) => (
my bad, you are right

2023-02-18 15:44 UTC, dejwi reviewed
last stuff

2023-02-18 15:44 UTC, dejwi commented on components/profile/overview/overview.tsx
> +          key="headerLoader"
again, change to this and remove `Partial<..>` from other components
```suggestion
    <AnimatePresence mode="wait">
      {isLoading || !data ? (
        <motion.div
          key="headerLoader"
```

2023-02-18 15:44 UTC, dejwi commented on components/common/Heading.tsx
> +)
again please move this to `/components/profile/common` and `SectionContainer` too

2023-02-18 16:13 UTC, mati-1 commented
lets go bro, I hope its the last one 😆

2023-02-18 16:21 UTC, dejwi reviewed
nice💪

2023-02-22 18:22 UTC, dejwi requested changes
Good job bro💪

each section should be in separate component and then they would be listed in `overview.tsx` because it gets messy there, I got lost multiple times in this file XD
but don't deal with it now, I should've told you earlier, there are more important things now

add optional wideoUrl to data object and add this section variant based on this
![image](https://user-images.githubusercontent.com/80927085/220716542-ad748f03-f5b4-4184-8d40-dfd7973cf111.png)

2023-02-22 18:22 UTC, dejwi commented on components/profile/overview/overview.tsx
> +                  </p>
let's ask about variants here tomorrow as well

2023-02-22 18:26 UTC, mati-1 commented on dummy-api/profile/overview.ts
> +  }
oh you are right, i forgot about that 😃

2023-02-22 18:31 UTC, mati-1 commented on components/profile/overview/regularity/regularity.tsx
> +          </p>
good idea

2023-02-22 18:38 UTC, mati-1 commented on components/profile/overview/overview.tsx
> +              </div>
you are right again

2023-02-22 18:38 UTC, mati-1 commented on components/profile/overview/overview.tsx
> +                  </p>
yes this is must have

2023-02-22 21:25 UTC, mati-1 commented on components/profile/overview/transfers/transfers.tsx
> +        </p>
aight

2023-02-22 22:17 UTC, dejwi requested changes
this and we're waiting for when you move types to swagger & adjust things to it here

2023-02-22 22:17 UTC, dejwi commented on components/profile/overview/transfers/transfers.tsx
> +          {transfer.type} ({transfer.date})
use existing helper
```suggestion
          {transfer.type} ({formatDate(transfer.date})
```

2023-02-22 22:17 UTC, dejwi commented on dummy-api/profile/overview.ts
> +  }[]
please don't ignore stuff from previous review
We do that because backend shouldn't worry about how we format data for display
```suggestion
  similarPlayers: {
    name: string
    image: string
    score: number
    premium: boolean
    age: number
    scoreTrend: 'up' | 'down'
    position: string
    team: string
    competition: string
  }[]
```
you'll have to adjust component as well

2023-02-22 22:17 UTC, dejwi commented on components/profile/overview/gameVideo/gameVideo.tsx
> +    </div>
can't we do `playerData.video ? ...` directly ?

2023-02-22 22:17 UTC, dejwi commented on components/profile/overview/overview.tsx
> +              <PlayerBaseData {...data?.playerData} />
```suggestion
              <PlayerBaseData {...data.playerData} />
```

2023-02-22 22:17 UTC, dejwi commented on components/profile/overview/overview.tsx
> +              {data?.carrer.map(carrer => (
```suggestion
              {data.carrer.map(carrer => (
```

2023-02-22 22:17 UTC, dejwi commented on components/profile/overview/overview.tsx
> +              <ExperiencePanel {...data?.experience} />
```suggestion
              <ExperiencePanel {...data.experience} />
```

2023-02-22 22:46 UTC, mati-1 commented on components/profile/overview/gameVideo/gameVideo.tsx
> +    </div>
in the future yes, but for now I just wanted to use this figma image which is already styled and has an icon on it

2023-02-22 23:00 UTC, dejwi commented on components/profile/overview/gameVideo/gameVideo.tsx
> +    </div>
I don't think you get what I meant, I'm talking about `{playerData.video ? <Image .. /> : ( .. ) }` instead of creating variable

2023-02-23 01:06 UTC, mati-1 commented on components/profile/overview/gameVideo/gameVideo.tsx
> +    </div>
aight haha

2023-02-23 11:10 UTC, dejwi requested changes
or maybe if you can do this fast separate each section into a component, this is REALLY hard to read

2023-02-23 11:10 UTC, dejwi commented on dummy-api/profile/overview.ts
> +  }
these are single panels + typo:), don't forget to adjust components
```suggestion
  career: IProfileCareerData
  lastMatch: {
    playerStandedOut: boolean
    data: IProfileMatchesSeason
  }
```

2023-02-23 15:51 UTC, dejwi requested changes
this and we're waiting for your swagger

2023-02-23 15:51 UTC, dejwi commented on components/profile/overview/similarPlayers/similarPlayers.tsx
> +            <p className="w-[12.5rem] text-body-xs text-darkAlpha-40">{`${d.position} w ${d.team}, ${d.age} lat`}</p>
you forgot about competition 🙏

2023-02-23 15:51 UTC, dejwi commented on dummy-api/profile/overview.ts
> +  }[]
oh I'm sorry I missed this XD we have score in this format in other endpoints, let's be consistent
```suggestion
  similarPlayers: {
    name: string
    image: string
    premium: boolean
    age: number
    position: string
    team: string
    competition: string
    score: {
      value: number
      trend: 'up' | 'down'
    }
  }[]
```

2023-02-25 20:16 UTC, dejwi requested changes
nice

2023-02-25 20:16 UTC, dejwi commented on components/profile/overview/overview.tsx
> +                  </p>
please check standedOut and playedWorse separately, we'll have more types later

2023-02-25 20:16 UTC, dejwi commented on components/profile/overview/regularity/regularity.tsx
> +          </p>
use additional.type for this

2023-02-25 20:16 UTC, dejwi commented on components/profile/overview/regularity/regularity.tsx
> +          />
```suggestion
          <Image
            src={additional.teamLogo}
            width={40}
            height={40}
            alt={name}
            className="icon-24"
          />
```
I'll fix the name later to have Url at the end

2023-02-25 20:32 UTC, mati-1 commented on components/profile/overview/regularity/regularity.tsx
> +          </p>
could you elaborate?

2023-02-25 20:38 UTC, mati-1 commented on components/profile/overview/regularity/regularity.tsx
> +          />
oh i didnt notice it

2023-02-25 23:27 UTC, dejwi approved these changes

2023-02-25 23:27 UTC, merged