Feat/pm 704 GitHub config
fe-playmaker/fe-playmaker pull request #3
Opened 2023-02-01 15:18 UTC by skrimusss

[PM-704](https://playmakerpro.atlassian.net/browse/PM-704)

### Task Description
Creating a config for the project

2023-02-01 16:17 UTC, dejwi requested changes
please look again into this default config and analyse how everything (of what we use) should be defined, don't repeat names:) https://github.com/tailwindlabs/tailwindcss/blob/master/stubs/defaultConfig.stub.js#L7

<img width="554" alt="image" src="https://user-images.githubusercontent.com/80927085/216094041-d0327e2b-0e46-4028-92b9-dc94622b984f.png">

not to mention I had to comment out whole `boxShadow` section to get intellisense working, of what I've seen tailwind doesn't support double nesting in config like you did in `boxShadow` and `spacing`, look at linked config for reference


and please use pull request labels, and describe what changes you've made in particular pr, `Creating a config for the project` could mean a lot of things not to mention `... GitHub config` title 😅


tough first tickettttt you got this bro🙏

2023-02-01 16:17 UTC, dejwi commented on client/next.config.js
> +	},
why do we need this ?

2023-02-01 16:17 UTC, dejwi commented on client/tailwind.config.js
> +		},
everything I've said above and we don't want to split it between margin/padding
```
spacing: {
	1: '0.125rem',
	2: '0.25rem',
	3: '0.5rem',
        ....
        ....

},
```

2023-02-01 17:42 UTC, skrimusss commented on client/next.config.js
> +	},
this allows to create a react component involving a clean svg

2023-02-01 17:42 UTC, skrimusss commented on client/tailwind.config.js
> +		},
done

2023-02-01 22:49 UTC, dejwi requested changes
When you're done making changes please always click this on the right side 
<img width="375" alt="image" src="https://user-images.githubusercontent.com/80927085/216182794-bceb5e3f-889c-4532-8610-130ed6ff6a00.png">



and next time as well please use labels (right side), when we'll start working normally the pull requests tab will be really messy
<img width="371" alt="image" src="https://user-images.githubusercontent.com/80927085/216181415-1982b619-1259-4398-abd2-526a910d67da.png">

2023-02-01 22:49 UTC, dejwi commented on client/tailwind.config.js
> +			},
you've missed one:D I think we can just remove it as tailwind by default has added transparent color

2023-02-02 15:52 UTC, skrimusss reviewed
fixed a few things after cr

2023-02-02 15:53 UTC, closed without merging