Feat/pm 889/navbar desktop
fe-playmaker/fe-playmaker pull request #35
Opened 2023-02-27 22:04 UTC by mati-1

[PM-889](https://playmakerpro.atlassian.net/browse/PM-889)

- added desktop navbar
- corrected layout structure
- corrected size of premium gradient

2023-02-28 23:26 UTC, dejwi requested changes
very nice, some minor comments

maybe we'll change media queries to for ex. sd, md, ld instead of full name (ex. smallDesktop) ?

2023-02-28 23:26 UTC, dejwi commented on app/layout.tsx
>          <div className=" mx-auto w-full max-w-screen-mediumDesktop">
move mobile navbar here as well

2023-02-28 23:26 UTC, dejwi commented on components/Navbar/navbar-desktop.tsx
> +          </div>
please remove `fill` from .svg files and set fill color here in styles, one is not correct and probably we'll be changing conditionally colors anyways

2023-02-28 23:26 UTC, dejwi commented on components/Navbar/common/nav-link.tsx
> +        pathname === href ? 'font-bold' : 'font-medium',
sexy solution

2023-02-28 23:28 UTC, dejwi commented on components/Navbar/navbar-desktop.tsx
> +          <Button text="Zaloguj się" intent="primary" size="small" />
I've noticed that our button looks weirder, it turns out our has paddingY 8px and on figma it's 10px, can you verify if our variants are correct?

2023-03-01 15:33 UTC, mati-1 commented on components/Navbar/navbar-desktop.tsx
> +          </div>
oh, i forgot about that

2023-03-01 15:34 UTC, mati-1 commented on components/Navbar/common/nav-link.tsx
> +        pathname === href ? 'font-bold' : 'font-medium',
😆

2023-03-01 15:35 UTC, mati-1 commented on components/Navbar/navbar-desktop.tsx
> +          <Button text="Zaloguj się" intent="primary" size="small" />
you re right, it will be corrected soon

2023-03-02 20:21 UTC, dejwi requested changes
nice, I really like that you've separated `search-input`💯

2023-03-02 20:21 UTC, dejwi commented on components/Navbar/navbar.tsx
> +  </nav>
set width and height here with class, because `width=""` and `height=""` would be in pixels not rem

2023-03-02 20:21 UTC, dejwi commented on components/Navbar/common/search-input.tsx
> +import SeachIcon from '@/icons/Search.svg'
typo
```suggestion
import SearchIcon from '@/icons/Search.svg'
```

2023-03-02 22:03 UTC, dejwi approved these changes

2023-03-02 22:03 UTC, merged