Feat/pm 888/tab overview desktop
fe-playmaker/fe-playmaker pull request #36
Opened 2023-03-03 01:28 UTC by mati-1

[PM-888](https://playmakerpro.atlassian.net/browse/PM-888)

this branch only has tab overview changes please make cr and after correcting the code dont merge i want all tabs and top profile in this branch

- changed main layout with desktop version
- added navbar
- added all sections of overview tab
- corrected tables (i hope good)

2023-03-03 18:46 UTC, dejwi requested changes
overall looks good💯

couple of things:

I don't really like this table change, I really wanted to avoid putting same height in multiple files, are you sure we can't do better ?
and you still rely on context rowHeight and expandedRowHeight on rows/main with paddingBottom (it's used in matches table) so that mixture is even worse

avatar border is cropped
![image](https://user-images.githubusercontent.com/80927085/222798723-5a53eb56-6488-496b-b8c6-b551240200ef.png)

can we make this chips not cropped on left ?
![image](https://user-images.githubusercontent.com/80927085/222798848-85cdc445-8896-4afa-b2fc-eb20ff1ec694.png)

and this matches table border shouldn't be connected everywhere (figma image below)
<img width="191" alt="image" src="https://user-images.githubusercontent.com/80927085/222799269-a853971b-e5f1-4126-92a9-996432579a86.png">

2023-03-03 18:46 UTC, dejwi commented on components/common/Button/Button.tsx
> +      extraSmall: 'w-4 h-4 md:w-5 md:h-5',
as we talked about it don't guess sizes

2023-03-03 19:41 UTC, mati-1 commented on components/common/Button/Button.tsx
> +      extraSmall: 'w-4 h-4 md:w-5 md:h-5',
i forgot to remove it

2023-03-03 20:21 UTC, mati-1 commented
i will be very grateful if you correct the tables to done your vision, it will take you much faster because you were building this component

2023-03-04 15:48 UTC, dejwi requested changes
I think this spacing is lil too big
<img width="234" alt="image" src="https://user-images.githubusercontent.com/80927085/222915342-e1558112-8ca6-4fea-8282-1315f3e883b3.png">

add `desktopSize` to button and please fixup the matches table border

2023-03-07 21:43 UTC, dejwi requested changes
mostly looks nice, good job💪

pointer (I know this component is a shit show😅)
<img width="266" alt="image" src="https://user-images.githubusercontent.com/80927085/223556761-e26a0392-f35d-46b8-9621-ef62b2197f94.png">

ŚŚŚŚ (in two tables) (+columns should wider but it'll be my task with tables)
<img width="184" alt="image" src="https://user-images.githubusercontent.com/80927085/223557734-dab1bac0-9d1e-4d84-b553-d1fe46cdf0eb.png">


header banner btn
(dev)
<img width="205" alt="image" src="https://user-images.githubusercontent.com/80927085/223558454-91fe0f13-1929-4255-8800-a25e577e269b.png">

(figma)
<img width="170" alt="image" src="https://user-images.githubusercontent.com/80927085/223558492-53c1f835-0520-48f3-bb66-0cfb0ee75e92.png">

and sections bottom paddings should be a little bigger

2023-03-11 16:00 UTC, dejwi approved these changes
- don't use AnimatePresence where it's not needed, it's so you can use exit animation but we didn't use it here (transfers, similar players) and I've looked into this because there were missing keys errors in browser console, look out for that as well bro!
- loaders still need to be corrected, tabs and whole page (more centered)
<img width="1613" alt="image" src="https://user-images.githubusercontent.com/80927085/224492915-35e2a9a4-fc91-41b0-b16c-da6ca9ae1548.png">

- and don't skip cr stuff !! I've mentioned in previous one that paddings in sections are off and you skipped that
- ^ pointer still needs to be fixed (picture with custom percentage passed - 90)
<img width="255" alt="image" src="https://user-images.githubusercontent.com/80927085/224494540-6b13322b-d4a1-4560-a98d-1675e1b2c252.png">

wel'll merge this as it is and changes above will come with separate pr

2023-03-11 16:18 UTC, merged