Feat/correct modal
fe-playmaker/fe-playmaker pull request #51
Opened 2023-03-11 19:07 UTC by mati-1

- corrected paddings
- added new simple functions for modal

2023-03-12 14:25 UTC, dejwi requested changes
this animation is now weird (transfers are still okay) can you look into this ?

https://user-images.githubusercontent.com/80927085/224550920-fa96b8e8-e571-45ef-8425-5379922ac551.mov

2023-03-12 14:25 UTC, dejwi commented on components/profile/header/searching-for-club-modal.tsx
> +  }, [open])
ios fix and maybe we can move it to Modal component itself ?
```suggestion
  useEffect(() => {
 if (open) {
      document.body.style.overflow = 'hidden'
      document.body.style.touchAction = 'none'
    } else {
      document.body.style.overflow = 'unset'
      document.body.style.touchAction = 'auto'
    }
  }, [open])
```

2023-03-12 18:03 UTC, mati-1 commented on components/profile/header/searching-for-club-modal.tsx
> +  }, [open])
nice 👍

2023-03-15 22:26 UTC, dejwi approved these changes

2023-03-17 14:23 UTC, merged