Feat/pm 906/pmscore line chart
fe-playmaker/fe-playmaker pull request #60
Opened 2023-03-20 19:26 UTC by mati-1

[PM-906](https://playmakerpro.atlassian.net/browse/PM-906)

- added line chart (still without data from api)
- unresolved bug with left Y axis line

2023-03-25 00:30 UTC, dejwi requested changes
nice, now make it use data from swagger/api

2023-04-10 21:59 UTC, dejwi requested changes

2023-04-10 21:59 UTC, dejwi commented on dummy-api/profile/overview.ts
> +      date: '5 lis ‘22',
that's not a date format 😅  formatting dates is our job not backend's

2023-04-11 09:03 UTC, mati-1 commented on dummy-api/profile/overview.ts
> +      date: '5 lis ‘22',
yes i know that but i forgot to change it 😆

2023-04-16 17:55 UTC, dejwi approved these changes

2023-04-16 22:13 UTC, merged