Feat/pm 958/adding teams page + last stats page
fe-playmaker/fe-playmaker pull request #81
Opened 2023-04-23 16:15 UTC by mati-1

[PM-958](https://playmakerpro.atlassian.net/browse/PM-958)

- added page for searching and adding club
- added modal with clubs
- added filtering club by name and gender
- added all needed figma states with illustations
- added loading state at last page while finishing the form

2023-04-23 17:27 UTC, dejwi requested changes

2023-04-23 17:27 UTC, dejwi commented on components/login-register/register/pages/adding-teams-page/modals/teams-modal.tsx
> +  const memoizedValues = useMemo(() => teams, [teams])
why something like this

2023-04-23 17:27 UTC, dejwi commented on components/login-register/register/pages/adding-teams-page/modals/teams-modal.tsx
> +  const debouncedValue = useDebounce(searchValue, 400)
if I'm guessing correctly
```suggestion
  const debouncedSearchValue = useDebounce(searchValue, 400)
```

2023-04-23 17:27 UTC, dejwi commented on components/login-register/register/utils.ts
> +  ninetyMinURL: '',
```suggestion
  90MinURL: '',
```

2023-04-23 17:27 UTC, dejwi commented on components/login-register/register/utils.ts
> +  competention: '',
typo:)

2023-04-23 17:27 UTC, dejwi commented on components/login-register/register/hooks.ts
> +  })
I don't think it should have an id param, have you meant a search value ?

2023-04-23 17:27 UTC, dejwi commented on components/Navbar/common/search-input.tsx
> +      className || 'sd:ml-[2.4rem] ld:ml-[7.2rem]',
maybe keep it like it was before and when you want to overwrite it just use a !, example: `ld:!ml-[2137rem]` it'll mark it as !important in css

2023-04-23 17:27 UTC, dejwi commented on dummy-api/register/lists.ts
> +          'https://s3-alpha-sig.figma.com/img/94c5/dff2/e8ea580956e28932941c06eec7757955?Expires=1682899200&Signature=YUnyOjQJ4ZmTVFgQ46mLcB~97kiB7euNIkpDZBOznLbtCNepmHxcuGU-T~-ETsywSKWA6VhLWbPihzKrR
you'll have to download these images and keep them in `/img/mock` and add them here with .src, there were some issues before in vercel deploy with figma blocking requests to images and I had to download all of them, as you can see in other dummy api files

2023-04-23 17:33 UTC, mati-1 commented on components/login-register/register/utils.ts
> +  ninetyMinURL: '',
eslint throwing an error when entering values into this object

2023-04-23 18:08 UTC, dejwi requested changes
and I don't understand why these hooks have an id param too, and this xx-modal key
\+ maybe move them to `/hooks/lists` with all the other hooks ?

(ss as it doesn't allow me to comment there)
<img width="480" alt="image" src="https://user-images.githubusercontent.com/80927085/233857007-db7875be-16c4-4d78-8885-044c264c252b.png">

2023-04-23 18:08 UTC, dejwi commented on components/login-register/register/hooks.ts
> +export const useTeamsList = (id: string, whenEnabled: boolean) =>
this should be `useClubsList`

2023-04-23 18:25 UTC, dejwi requested changes

2023-04-23 18:25 UTC, dejwi commented on components/login-register/register/pages/adding-teams-page/modals/teams-modal.tsx
> +  const { data: teams, isFetching } = useTeamsList(
if value is cached we don't have to show a loader
```suggestion
  const { data: teams, isLoading } = useTeamsList(
```

2023-04-23 18:25 UTC, dejwi commented on components/login-register/register/pages/adding-teams-page/modals/teams-modal.tsx
> +  }, [debouncedValue, gender, queryClient])
I think it's not necessary, clubs filtered by word for ex. 'gdansk' will still return the same list when you type it again in like a few seconds so no point in displaying loader

correct me if I'm wrong
```suggestion
```

2023-04-23 19:23 UTC, mati-1 commented on components/login-register/register/pages/adding-teams-page/modals/teams-modal.tsx
> +  }, [debouncedValue, gender, queryClient])
we will fetch values by search value in the future right? I think is needed (but not right now, this code functions as what it will looks like in the future)

2023-04-23 19:32 UTC, dejwi commented on components/login-register/register/pages/adding-teams-page/modals/teams-modal.tsx
> +  }, [debouncedValue, gender, queryClient])
you didn't explain why it's needed

yes we'll probably fetch by search value but the needed part is passing search value to useQuery hook and into queryKey so it will use different cached value

`queryClient.invalidateQueries`  is invalidating specific cache data, it's used when for example you update some todo on database, and now your previously cached todos list is out of date, so you invalidate it to get up to date data

here we don't have to invalidate data

2023-04-23 20:35 UTC, mati-1 commented on components/login-register/register/pages/adding-teams-page/modals/teams-modal.tsx
> +  }, [debouncedValue, gender, queryClient])
okay, thank you 💯

2023-04-24 20:39 UTC, dejwi requested changes

2023-04-24 20:39 UTC, dejwi commented on components/login-register/register/pages/adding-teams-page/modals/teams-modal.tsx
> +const EmptyCitiesMessage = () => (
prob typo
```suggestion
const InitialEmptyMessage = () => (
```

2023-04-24 20:39 UTC, dejwi commented on components/login-register/register/utils.ts
> +  competention: '',
please fix this typo :)

2023-04-24 20:39 UTC, dejwi commented on hooks/lists/clubs.ts
> +  })
enabled shouldn't depend on search value because maybe somewhere later we'll use a whole clubs lists

I'll correct this later with other swagger types so this uses a filters object infered from query params

```suggestion
export const useClubsList = (searchValue?: string, enabled?: boolean) =>
  useQuery({
    queryKey: ['club-list', searchValue],
    queryFn: returnAfterTime(clubs, 200),
    enabled,
    refetchOnWindowFocus: false,
    initialData: [{ id: '', name: '', gender: 'MALE', teams: [] }],
  })
```

2023-04-24 21:58 UTC, dejwi requested changes

2023-04-24 21:58 UTC, dejwi commented on components/login-register/register/utils.ts
> +  competention: '',
fix this typo!!
```suggestion
  competition: '',
```

2023-04-24 22:17 UTC, merged