Refactor/pm 1016/refactor base data section
fe-playmaker/fe-playmaker pull request #96
Opened 2023-05-23 20:38 UTC by mati-1

[PM-1016](https://playmakerpro.atlassian.net/browse/PM-1016)

### Task Description

- added edit buttons for two sections
- added citizenships and languages to base data section
- refactored jsx structure, basically for more alternative positions 
- added blured titles based on login status

2023-05-23 21:02 UTC, mati-1 commented on components/profile/overview/baseData/playerBaseData.tsx
> +  const altPositionsNames = altPositions.map(pos => pos.name)
How can I do this better?

2023-05-23 21:04 UTC, mati-1 commented on components/profile/overview/baseData/playerBaseData.tsx
> +                          altPositionsNames.includes(name) &&
includes are better instead of '===' in this case?

2023-05-23 21:06 UTC, mati-1 commented on components/profile/common/editButton.tsx
> +)
I'll add more props in the future

2023-05-23 21:06 UTC, mati-1 commented on components/profile/overview/baseData/helpers.ts
> +}
this is good? how can i do it better?

2023-05-23 21:07 UTC, mati-1 commented on components/profile/overview/baseData/helpers.ts
> +}
and generally this function is correct?

2023-05-23 21:07 UTC, mati-1 commented on components/profile/overview/baseData/helpers.ts
> +export const getBaseData = ({
and generally this function is correct?

2023-05-25 19:49 UTC, dejwi commented on components/profile/overview/baseData/helpers.ts
> +}
you could create type alias above for better readability 
```
type PlayerData = TProfileOverview['playerData']

interface IProps {
     age: PlayerData['age']
     ...
```

2023-05-25 19:56 UTC, dejwi commented on components/profile/overview/baseData/helpers.ts
> +export const getBaseData = ({
is this `soccerFieldData` based render better than creating some reusable components ? Idk it's kinda a chaos there in playerBaseData section but what do you think ? Just asking

2023-05-25 19:56 UTC, dejwi commented on components/profile/overview/baseData/playerBaseData.tsx
> +  const altPositionsNames = altPositions.map(pos => pos.name)
Do exactly what ?

2023-05-25 19:59 UTC, dejwi commented on components/profile/overview/careerSeason/careerSeason.tsx
> +        {status === 'authenticated' && <EditButton />}
it's not set as ready for review but because user is signed in, it doesn't mean it's his own profile, you have to use `ProfileContext` and check against `ownProfile` from it

2023-05-25 21:00 UTC, mati-1 commented on components/profile/overview/baseData/playerBaseData.tsx
> +  const altPositionsNames = altPositions.map(pos => pos.name)
const altPositionsNames = altPositions.map(pos => pos.name)

2023-05-26 14:05 UTC, mati-1 commented on components/profile/overview/careerSeason/careerSeason.tsx
> +        {status === 'authenticated' && <EditButton />}
yes bro you're right, but I'm not sure because I dont know exactly what the context of the profile will look like

2023-05-26 14:06 UTC, mati-1 commented on components/profile/overview/baseData/helpers.ts
> +export const getBaseData = ({
hmm, indeed

2023-05-28 19:25 UTC, dejwi commented on components/profile/overview/careerSeason/careerSeason.tsx
> +        {status === 'authenticated' && <EditButton />}
wdym ? context is typed and for now has `id` and helper boolean `ownProfile`

2023-06-02 21:50 UTC, mati-1 commented on components/profile/overview/careerSeason/careerSeason.tsx
> +        {status === 'authenticated' && <EditButton />}
ok bro 💯

2023-06-12 21:55 UTC, dejwi commented on components/login-register/common/Input/toggleSwitch.tsx
> +  setCtxValue: Dispatch<SetStateAction<any>>
can you give me an example type that you would like to replace `any` with ?

2023-06-12 22:37 UTC, dejwi requested changes
good job💯

I see that there are some `md:` instead of `sd:` in your components (not only this pr - register stuff too) can you verify that they actually have to be md: instead of sd:

2023-06-12 22:37 UTC, dejwi commented on components/profile/overview/baseData/playerBaseData.tsx
> +                      )}
I think `,` is on desktop as well + you can use in situations like this `sd:hidden` instead of useDesktop hook

2023-06-12 22:37 UTC, dejwi commented on components/profile/overview/careerSeason/careerSeason.tsx
> +        {status === 'authenticated' && ownProfile && <EditButton />}
unnecessary
```suggestion
        {ownProfile && <EditButton />}
```

2023-06-12 22:37 UTC, dejwi commented on components/profile/overview/baseData/baseData.tsx
> +        {status === 'authenticated' && ownProfile && (
unnecessary
```suggestion
        {ownProfile && (
```

2023-06-12 22:37 UTC, dejwi commented on components/profile/overview/baseData/modals/EditBaseDataModal.tsx
> +  const [selectedGender, setSelectedGender] = useState(gender)
I think we have to fuse everything with useForm, it would allow us to do full form validation and just keep everything concise

2023-06-12 22:37 UTC, dejwi commented on components/profile/overview/baseData/helpers.ts
> +}
oh sorry, you can `IProps extends Pick<TProfileOverview['playerData'], 'age' | 'location' ....>`

2023-06-13 10:25 UTC, mati-1 commented on components/profile/overview/baseData/playerBaseData.tsx
> +                      )}
good point

2023-06-13 10:27 UTC, mati-1 commented on components/profile/overview/baseData/modals/EditBaseDataModal.tsx
> +  const [selectedGender, setSelectedGender] = useState(gender)
hmm okay, i'll try

2023-06-14 22:10 UTC, mati-1 commented
> good job💯
> 
> I see that there are some `md:` instead of `sd:` in your components (not only this pr - register stuff too) can you verify that they actually have to be md: instead of sd:

i use md in the register cos it looks more correct n the fixed button styles arent wrong (instead of sd)

2023-06-15 21:23 UTC, dejwi approved these changes

2023-06-15 21:23 UTC, merged