Refactor/pm 1058/saving id instead of name
fe-playmaker/fe-playmaker pull request #97
Opened 2023-06-17 15:09 UTC by mati-1

[PM-1058](https://playmakerpro.atlassian.net/browse/PM-1058)

### Task Description

- added updating user data modal
- added missing data in the base data section
- added replacing bolded letters by search value
- changed logic for selecting item by id
- fixed responsiveness in the register and login pages
- removed related to incorrect email errors on login page

2023-06-19 18:31 UTC, mati-1 commented on components/login-register/register/pages/stats-page/stats-page.tsx
> +            onChange={({ target: { value } }) => setFirstUrlValue(value)}
hmm, now it looks much better imo

2023-06-19 18:34 UTC, mati-1 commented on components/login-register/common/Input/toggleSwitch.tsx
oh my gooood 😿

2023-06-19 18:35 UTC, mati-1 commented on components/login-register/register/pages/positions-page/positions-page.tsx
> +  const { data: positionsList, isLoading } = usePositionsList(openMainModal)
good

2023-06-19 18:39 UTC, mati-1 commented on components/login-register/register/register-context.tsx
> +  team: '',
good point

2023-06-19 21:02 UTC, mati-1 commented on components/profile/overview/baseData/helpers.ts
> +    Wiek: `${age} lat (${new Date(born).getFullYear()})`,
why is this incorrect? 🤔

2023-06-19 21:03 UTC, mati-1 commented on components/login-register/register/pages/positions-page/helpers.tsx
>        return <GoalKeeper className={clsx(styles, className)} />
yeah, i'd forgotten bout that

2023-06-19 21:03 UTC, mati-1 commented on components/login-register/common/Loading/modal-loader.tsx
> +)
good point

2023-06-19 21:05 UTC, mati-1 commented on components/login-register/common/Input/toggleSwitch.tsx
>    }
cos when the user spam the button, the animation is bugged (i think in this case we have to use mf)

2023-06-19 22:28 UTC, mati-1 commented on components/login-register/register/pages/positions-page/helpers.tsx
>        return <GoalKeeper className={clsx(styles, className)} />
i'll just put position names, for now

2023-06-20 01:14 UTC, mati-1 commented on components/login-register/common/Input/toggleSwitch.tsx
> +      setCtxValue(newValue)
indeed

2023-06-21 08:26 UTC, dejwi requested changes
move the input field to components and I think we can go with this

2023-06-23 07:32 UTC, dejwi approved these changes

2023-06-23 07:32 UTC, merged